export const papeterie = [
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-goldveredelung-samira-kerem.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-dankeskarte-timon-tamara.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-modern-frisch-individuell-tamara-timon.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-sitzplan-leiter-scheune-wildblumen.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-dankeskarte-tamara-timon.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-fotobox.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-getraenkekarte-rahmen-tisch.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-menuekarte-kraftpapier-scheune.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-dankesgeschenk-label-kerze.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-dankeskarte-samira-kerem.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-sitzplan-leiter-waescheklammer.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-blau-quadratisch-blumen-tamara-timon.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-jessi-michael.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-sara-patrick-typographie.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-umschlag.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-valerie-max.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-valerie-max-kraftpapier.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-eleganter-sitzplan-bilderrahmen.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-gastgeschenk-honig-label-kraftpapier.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-elegant-siegel.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-sitzplan-rahmen.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-sitzplan-tischaufteilung.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-sara-patrick-faecher.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-save-the-date-elegant-minimalistisch-tamara-timon.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-gold-natur-blaetter-tamara-timon.jpg",
]

export const stories = [
  'stories/samira_kerem/ironleaves-photography-stories-samira-kerem-slider-tanz-ungestellt.jpg',
  'stories/julia_martin/ironleaves-photography-stories-julia-martin-slider-tanzend-in-der-stadt.jpg',
  'stories/samira_kerem/ironleaves-photography-stories-samira-kerem-slider-wald-verliebt.jpg',
  'stories/julia_martin/ironleaves-photography-stories-julia-martin-slider-bruecke-urban.jpg',
  'stories/sandra_jonas_hochzeit/ironleaves-photography-stories-sandra-jonas-hochzeit-slider-shooting-kuss-park-hofgarten-bayreuth.jpg',
  'stories/sandra_jonas_hochzeit/ironleaves-photography-stories-sandra-jonas-hochzeit-slider-shooting-schnappschuss.jpg',
  'stories/samira_kerem/ironleaves-photography-stories-samira-kerem-slider-wald-panorama.jpg',
  'stories/julia_martin/ironleaves-photography-stories-julia-martin-slider-naehe-natuerlichkeit.jpg',
  'stories/valerie_max/ironleaves-photography-stories-valerie-max-hochzeitskleid.jpg',
  'stories/samira_kerem/ironleaves-photography-stories-samira-kerem-slider-kuss-wiese-sonnenuntergang.jpg',
  'stories/valerie_max/ironleaves-photography-stories-valerie-max-laecheln.jpg',
  'stories/sandra_jonas_standesamt/ironleaves-photography-stories-sandra-jonas-standesamt-slider-reportage-kuss-verheiratet.jpg',
  'stories/samira_kerem/ironleaves-photography-stories-samira-kerem-slider-lensflare.jpg',
  'stories/julia_martin/ironleaves-photography-stories-julia-martin-slider-stadtpark.jpg',
  'stories/sandra_jonas_hochzeit/ironleaves-photography-stories-sandra-jonas-hochzeit-slider-shooting-probe-tanz-parkplatz.jpg',
  'stories/julia_martin/ironleaves-photography-stories-julia-martin-slider-sonnenuntergang-shooting.jpg',
  'stories/sandra_jonas_hochzeit/ironleaves-photography-stories-sandra-jonas-hochzeit-slider-shooting-verliebt-vertraulichkeit.jpg',
  'stories/sandra_jonas_hochzeit/ironleaves-photography-stories-sandra-jonas-hochzeit-slider-reportage-seifenblasen-einmarsch.jpg',
  'stories/julia_martin/ironleaves-photography-stories-julia-martin-slider-blick-in-die-augen.jpg',
  'stories/sandra_jonas_standesamt/ironleaves-photography-stories-sandra-jonas-standesamt-slider-reportage-tanzend-ungestellt.jpg',
  'stories/julia_martin/ironleaves-photography-stories-julia-martin-slider-brautpaar-laufend.jpg',
  'stories/valerie_max/ironleaves-photography-stories-valerie-max-eskimo.jpg',
  'stories/sandra_jonas_standesamt/ironleaves-photography-stories-sandra-jonas-standesamt-slider-reportage-spontaner-kuss.jpg',
  'stories/samira_kerem/ironleaves-photography-stories-samira-kerem-slider-lens-flare.jpg',
  'stories/sandra_jonas_standesamt/ironleaves-photography-stories-sandra-jonas-standesamt-slider-reportage-schlossgarten-eckersdorf.jpg',
  'stories/valerie_max/ironleaves-photography-stories-valerie-max-wald-rueckenansicht.jpg',
  'stories/valerie_max/ironleaves-photography-stories-valerie-max-ehrlich-ungestellt.jpg',
  'stories/sandra_jonas_hochzeit/ironleaves-photography-stories-sandra-jonas-hochzeit-slider-reportage-shooting-pfuetze-spiegelung-abends.jpg',
]

// ts complains unless this is here
export default {}
