export const papeterie = [
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-goldveredelung-samira-kerem.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-dankeskarte-timon-tamara.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-sitzplan-leiter-scheune-wildblumen.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-dankeskarte-tamara-timon.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-fotobox.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-getraenkekarte-rahmen-tisch.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-menuekarte-kraftpapier-scheune.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-dankesgeschenk-label-kerze.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-dankeskarte-samira-kerem.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-sitzplan-leiter-waescheklammer.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-jessi-michael.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-sara-patrick-typographie.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-umschlag.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-valerie-max.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-valerie-max-kraftpapier.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-eleganter-sitzplan-bilderrahmen.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-gastgeschenk-honig-label-kraftpapier.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-elegant-siegel.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-sitzplan-rahmen.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-sitzplan-tischaufteilung.jpg",
  "papeterie/ironleaves-photography-individuelle-papeterie-slider-einladungskarte-sara-patrick-faecher.jpg",
]

export default {}
